/* WAVE v0.1.0 — numerical core. MIT © 2026 existentialblu.
   WAT reference: main fcd24e08e06ee0f0d42e648185f03bda64e2bce6 (v0.5).
   Independent amplitude-envelope pipeline; never a clinical event scorer. */
const Wave=(()=>{
'use strict';
const VERSION='0.1.0',FS=.5,DEFAULTS={band:'main',smooth:120,threshold:.6,relativeThreshold:.12,minPacket:120,bridge:30,minSession:30,trim:300,leakLimit:24,gap:2,source:'prefer',clockShift:0};
const SOS={main:[[.011324865405187116,.022649730810374233,.011324865405187116,1,-1.3626613408836916,.6513212052513601],[1,0,-1,1,-1.524530452512027,.5773502691896257],[1,-2,1,1,-1.9096063139253172,.9212044612741357]],narrow:[[.0020976317068894883,.004195263413778977,.0020976317068894883,1,-1.7021899355630097,.7535540501027941],[1,0,-1,1,-1.675602628548287,.8175876346856226],[1,-2,1,1,-1.9059791067550536,.9268111225874168]],wide:[[.013384535450408243,.026769070900816486,.013384535450408243,1,-1.3295254439288902,.6172122570322245],[1,0,-1,1,-1.5194330037724004,.5543090514527689],[1,-2,1,1,-1.936342306258005,.941455902297882]]};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function sum(a){let s=0;for(const x of a)s+=x;return s}
const mean=a=>a.length?sum(a)/a.length:0;
function quantile(a,q){if(!a.length)return null;const b=Float64Array.from(a).sort(),p=(b.length-1)*q,i=Math.floor(p);return b[i]+(b[Math.min(i+1,b.length-1)]-b[i])*(p-i)}
function select(a,valid){const out=[];for(let i=0;i<a.length;i++)if(valid[i])out.push(a[i]);return out}
function sd(a){const m=mean(a);let v=0;for(const x of a)v+=(x-m)**2;return Math.sqrt(v/Math.max(1,a.length))}
function corr(a,b,valid){let n=0,x=0,y=0,xx=0,yy=0,xy=0;for(let i=0;i<a.length;i++)if(!valid||valid[i]){n++;x+=a[i];y+=b[i];xx+=a[i]*a[i];yy+=b[i]*b[i];xy+=a[i]*b[i]}const den=Math.sqrt(Math.max(0,(n*xx-x*x)*(n*yy-y*y)));return den>1e-12?(n*xy-x*y)/den:null}
function reflect(i,n,duplicate=true){if(n===1)return 0;while(i<0||i>=n)i=i<0?(duplicate?-i-1:-i):(duplicate?2*n-i-1:2*n-i-2);return i}
function rolling(x,seconds){const size=Math.floor(seconds*FS/2)*2+1,h=size>>1,n=x.length,y=new Float64Array(n);if(!n)return y;let s=0;for(let j=-h;j<=h;j++)s+=x[reflect(j,n)];for(let i=0;i<n;i++){y[i]=s/size;s+=x[reflect(i+h+1,n)]-x[reflect(i-h,n)]}return y}
function filter(x,band='main'){
 const sos=SOS[band];if(!sos)throw Error('Unsupported wave band');if(x.length<4)throw Error('Signal too short');const p=Math.min(300,x.length-1),ext=new Float64Array(x.length+2*p);
 for(let i=0;i<p;i++){ext[i]=2*x[0]-x[p-i];ext[p+x.length+i]=2*x[x.length-1]-x[x.length-2-i]}ext.set(x,p);
 function pass(a){let out=a;for(const [b0,b1,b2,,a1,a2] of sos){const next=new Float64Array(out.length),gain=(b0+b1+b2)/(1+a1+a2);let z1=(gain-b0)*out[0],z2=(b2-a2*gain)*out[0];for(let i=0;i<out.length;i++){const v=out[i],y=b0*v+z1;z1=b1*v-a1*y+z2;z2=b2*v-a2*y;next[i]=y}out=next}return out}
 const forward=pass(ext);forward.reverse();const back=pass(forward);back.reverse();return back.slice(p,p+x.length);
}
function radix(re,im,inverse=false){const n=re.length;if(n!==im.length||n<1||(n&(n-1)))throw Error('FFT needs a power of two');for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=n;len*=2){const angle=(inverse?2:-2)*Math.PI/len,wr=Math.cos(angle),wi=Math.sin(angle);for(let i=0;i<n;i+=len){let ur=1,ui=0;for(let j=0;j<len/2;j++){const a=i+j,b=a+len/2,vr=re[b]*ur-im[b]*ui,vi=re[b]*ui+im[b]*ur;re[b]=re[a]-vr;im[b]=im[a]-vi;re[a]+=vr;im[a]+=vi;const t=ur*wr-ui*wi;ui=ur*wi+ui*wr;ur=t}}}if(inverse)for(let i=0;i<n;i++){re[i]/=n;im[i]/=n}}
function fft(real,imag=null,inverse=false){const n=real.length,re=Float64Array.from(real),im=imag?Float64Array.from(imag):new Float64Array(n);if(!n)return{re,im};if(inverse){for(let i=0;i<n;i++)im[i]*=-1;const v=fft(re,im);for(let i=0;i<n;i++){v.re[i]/=n;v.im[i]/=-n}return v}if(!(n&(n-1))){radix(re,im);return{re,im}}
 let m=1;while(m<2*n-1)m*=2;const ar=new Float64Array(m),ai=new Float64Array(m),br=new Float64Array(m),bi=new Float64Array(m);
 for(let i=0;i<n;i++){const angle=Math.PI*((i*i)%(2*n))/n,c=Math.cos(angle),s=Math.sin(angle);ar[i]=re[i]*c+im[i]*s;ai[i]=im[i]*c-re[i]*s;br[i]=c;bi[i]=s;if(i){br[m-i]=c;bi[m-i]=s}}
 radix(ar,ai);radix(br,bi);for(let i=0;i<m;i++){const r=ar[i]*br[i]-ai[i]*bi[i];ai[i]=ar[i]*bi[i]+ai[i]*br[i];ar[i]=r}radix(ar,ai,true);
 for(let i=0;i<n;i++){const angle=Math.PI*((i*i)%(2*n))/n,c=Math.cos(angle),s=Math.sin(angle);re[i]=ar[i]*c+ai[i]*s;im[i]=ai[i]*c-ar[i]*s}return{re,im};
}
function envelope(y,smooth=120){const n=y.length,p=600,padded=new Float64Array(n+2*p);for(let i=0;i<padded.length;i++)padded[i]=y[reflect(i-p,n,false)];const v=fft(padded),len=v.re.length;for(let i=1;i<len;i++){const mult=len%2===0&&i===len/2?1:(i<(len+1)/2?2:0);v.re[i]*=mult;v.im[i]*=mult}const h=fft(v.re,v.im,true),a=new Float64Array(n);for(let i=0;i<n;i++)a[i]=Math.hypot(h.re[p+i],h.im[p+i])/Math.SQRT2;return rolling(a,smooth)}
function runs(mask){const out=[];let b=-1;for(let i=0;i<=mask.length;i++){if(i<mask.length&&mask[i]){if(b<0)b=i}else if(b>=0){out.push([b,i]);b=-1}}return out}
function expandBad(bad,radius){const n=bad.length,out=new Uint8Array(n);let s=0;for(let i=0;i<=Math.min(radius,n-1);i++)s+=bad[i];for(let i=0;i<n;i++){out[i]=s>0;if(i-radius>=0)s-=bad[i-radius];if(i+radius+1<n)s+=bad[i+radius+1]}return out}
function packetize(a,threshold,valid,opts=DEFAULTS){const m=Uint8Array.from(a,v=>v>=threshold);for(const [b,e] of runs(Uint8Array.from(m,v=>!v)))if(b>0&&e<m.length&&(e-b)/FS<=opts.bridge)m.fill(1,b,e);const out=[],invalid=new Uint32Array(valid.length+1);for(let i=0;i<valid.length;i++)invalid[i+1]=invalid[i]+!valid[i];for(const [b,e] of runs(m)){if((e-b)/FS<opts.minPacket||b===0||e===m.length||invalid[e+1]-invalid[b-1])continue;let peak=b;for(let i=b+1;i<e;i++)if(a[i]>a[peak])peak=i;out.push({start:b*2,end:e*2,peakTime:peak*2,duration:(e-b)/30,rise:(peak-b)/30,fall:(e-peak)/30,peak:a[peak]})}return out}
function parseEDF(buffer){if(buffer.byteLength<256)throw Error('EDF header is missing');const view=new DataView(buffer),decoder=new TextDecoder('ascii');const text=(o,n)=>{if(o<0||o+n>buffer.byteLength)throw Error('Truncated EDF header');return decoder.decode(new Uint8Array(buffer,o,n)).trim()},number=(o,n)=>Number(text(o,n));const ns=number(252,4),bytes=number(184,8),duration=number(244,8),declared=number(236,8),reserved=text(192,44);
 if(!Number.isInteger(ns)||ns<1||ns>512||!Number.isInteger(bytes)||bytes<256*(ns+1)||bytes>buffer.byteLength||!(duration>0)||!Number.isInteger(declared)||declared< -1)throw Error('Invalid EDF structure');if(/EDF\+D/.test(reserved))throw Error('Discontinuous EDF+D is unsupported; gaps cannot be inferred safely');
 let pos=256;const channels=Array.from({length:ns},()=>({}));for(const [key,width,isNumber] of [['label',16],['transducer',80],['unit',8],['pmin',8,1],['pmax',8,1],['dmin',8,1],['dmax',8,1],['prefilter',80],['samples',8,1],['reserved',32]]){for(const ch of channels){ch[key]=isNumber?Number(text(pos,width)):text(pos,width);pos+=width}}
 let recordBytes=0;for(const ch of channels){if(!Number.isInteger(ch.samples)||ch.samples<0)throw Error('Invalid samples per record');ch.offset=recordBytes;recordBytes+=ch.samples*2}if(!recordBytes)throw Error('EDF has no sample data');const payload=buffer.byteLength-bytes;if(payload%recordBytes)throw Error('Truncated EDF record');const available=payload/recordBytes;if(declared>=0&&declared!==available)throw Error('EDF record count does not match payload');
 const [dd,mm,yy]=text(168,8).split('.').map(Number),[hh,mi,sec]=text(176,8).split('.').map(Number),year=yy<85?2000+yy:1900+yy,start=Date.UTC(year,mm-1,dd,hh,mi,sec),date=new Date(start);if(!Number.isFinite(start)||date.getUTCDate()!==dd||date.getUTCMonth()!==mm-1||hh>23||mi>59||sec>59)throw Error('Invalid EDF timestamp');
 function read(ch){if(!ch||!ch.samples)throw Error('Required signal is missing');if(![ch.pmin,ch.pmax,ch.dmin,ch.dmax].every(Number.isFinite)||ch.dmax===ch.dmin)throw Error('Invalid signal calibration');const n=available*ch.samples;if(n>100000000)throw Error('Signal too large for this browser tool');const out=new Float64Array(n),scale=(ch.pmax-ch.pmin)/(ch.dmax-ch.dmin);for(let r=0;r<available;r++){const base=bytes+r*recordBytes+ch.offset;for(let i=0;i<ch.samples;i++)out[r*ch.samples+i]=(view.getInt16(base+2*i,true)-ch.dmin)*scale+ch.pmin}return{data:out,fs:ch.samples/duration,unit:ch.unit,maximum:Math.max(ch.pmin,ch.pmax)}}
 return{start,duration:available*duration,records:available,channels,read};
}
function at2s(edf,ch,start,n){const c=edf.read(ch);if(!(.05<=c.fs&&c.fs<=1000))throw Error('Unsupported sampling rate');const out=new Float64Array(n),offset=(start-edf.start)/1000;for(let i=0;i<n;i++){const p=(i*2+offset)*c.fs,lo=Math.floor(p),f=p-lo;if(lo<0||lo>=c.data.length){out[i]=NaN;continue}out[i]=c.data[lo]+(c.data[Math.min(lo+1,c.data.length-1)]-c.data[lo])*f}return out}
function flowMV(edf){const ch=edf.channels.find(c=>/^Flow(?:\.|$)/i.test(c.label));if(!ch)throw Error('No calibrated Flow channel');const c=edf.read(ch),unit=c.unit.replace(/\s/g,'').toLowerCase(),scale=unit==='l/s'?60:unit==='l/min'?1:null;if(scale===null)throw Error('Unsupported airflow units: '+c.unit);if(c.fs<5||c.fs>200)throw Error('Airflow sampling rate outside 5–200 Hz');const n=Math.floor(edf.duration*FS),out=new Float64Array(n),bad=new Uint8Array(n);for(let k=0;k<n;k++){let a=Math.round(k*2*c.fs),b=Math.min(c.data.length,Math.round((k+1)*2*c.fs)),s=0;for(let i=a;i<b;i++){const v=c.data[i];if(!Number.isFinite(v)||Math.abs(v)>Math.max(5,c.maximum*.99))bad[k]=1;s+=Math.max(0,Number.isFinite(v)?v:0)}out[k]=s/(b-a)*scale}return{mv:rolling(out,12),bad,raw:c.data,fs:c.fs,flowScale:scale};}
function prepare(pldBuffer,brpBuffer,opts){let pld=pldBuffer?parseEDF(pldBuffer):null,brp=brpBuffer?parseEDF(brpBuffer):null;const device=pld&&pld.channels.find(c=>/^MinVent(?:\.|$)/i.test(c.label));let source,start,duration,mv,derived=null,flow=null,bad;
 if(opts.source!=='flow'&&device){if(!/l\/min/i.test(device.unit))throw Error('Unexpected minute ventilation units');source='Device MV';start=pld.start;duration=pld.duration;mv=at2s(pld,device,start,Math.floor(duration*FS));bad=Uint8Array.from(mv,v=>!Number.isFinite(v)||v<0||v>=device.pmax)}else{if(!brp)throw Error(opts.source==='device'?'No PLD minute ventilation':'No BRP airflow available');if(opts.source==='device')throw Error('No PLD minute ventilation');flow=flowMV(brp);source='Flow-derived';start=brp.start;duration=brp.duration;mv=flow.mv;bad=flow.bad}
 if(!mv.length)throw Error('Header-only recording');const n=mv.length,channel=(pattern,mult=1)=>{const ch=pld?.channels.find(c=>pattern.test(c.label));return ch?Float64Array.from(at2s(pld,ch,start,n),v=>v*mult):null};
 const leak=channel(/^Leak(?:\.|$)/i,pld?.channels.find(c=>/^Leak(?:\.|$)/i.test(c.label))?.unit.toLowerCase()==='l/min'?1:60),pressure=channel(/^Press(?:\.|$)/i),epap=channel(/^EprPress(?:\.|$)/i),flowLimit=channel(/^FlowLim(?:\.|$)/i),target=channel(/^TgtVent(?:\.|$)/i);let support='Unknown';if(pressure&&epap){const delta=Array.from(pressure,(v,i)=>v-epap[i]).filter(Number.isFinite);support=delta.length&&quantile(delta,.95)-quantile(delta,.05)>.5?'Variable support':'Fixed support'}
 return{start,duration,source,mv,bad,leak,pressure,epap,flowLimit,target,support,pld,brp};
}
function analyzeSignal(input,settings={}){const o={...DEFAULTS,...settings},x=Float64Array.from(input.mv),n=x.length,bad=Uint8Array.from(input.bad||x,v=>input.bad?!!v:!Number.isFinite(v)),originalBad=bad.slice();if(n<o.minSession*30)return{skipped:'Session shorter than minimum'};let last=-1;for(let i=0;i<n;i++)if(!bad[i]){if(last<0)x.fill(x[i],0,i);else for(let j=last+1;j<i;j++)x[j]=x[last]+(x[i]-x[last])*(j-last)/(i-last);last=i}if(last<0)return{skipped:'No valid ventilation'};x.fill(x[last],last+1);for(let i=0;i<Math.min(10,n);i++)x[i]=x[Math.min(10,n-1)];if(input.leak)for(let i=0;i<n;i++)if(!Number.isFinite(input.leak[i])||input.leak[i]>o.leakLimit)bad[i]=1;
 const expanded=expandBad(bad,60),valid=new Uint8Array(n),edge=Math.round(o.trim*FS);for(let i=edge;i<n-edge;i++)valid[i]=!expanded[i];const count=sum(valid);if(count<300)return{skipped:'Less than ten usable minutes'};
 const y=filter(x,o.band),a=envelope(y,o.smooth),base=rolling(x,300),relative=Float64Array.from(a,(v,i)=>v/Math.max(base[i],1));const clean=select(a,valid),rel=select(relative,valid),packets=packetize(a,o.threshold,valid,o),relativePackets=packetize(relative,o.relativeThreshold,valid,o);const frac=(arr,th)=>{let c=0;for(let i=0;i<n;i++)if(valid[i]&&arr[i]>=th)c++;return c/count};
 const variants=[['0.4 L/min',a,.4],['0.6 L/min',a,.6],['0.8 L/min',a,.8],['8% of local MV',relative,.08],['12% of local MV',relative,.12],['16% of local MV',relative,.16]].map(([label,v,threshold])=>{const p=packetize(v,threshold,valid,o);return{label,fraction:frac(v,threshold),packets:p.length,longPackets:p.filter(p=>p.duration>=6&&p.duration<=15).length,medianDuration:quantile(p.map(p=>p.duration),.5)}});
 const meta={start:input.start,duration:input.duration,source:input.source,support:input.support,hasLeak:!!input.leak,hasPressure:!!input.epap,usableSeconds:count*2,usableFraction:count/n,mvMedian:quantile(select(x,valid),.5),amplitude:quantile(clean,.5),relativeAmplitude:quantile(rel,.5),contrast:quantile(clean,.9)/Math.max(quantile(clean,.1),1e-9),fraction:frac(a,o.threshold),relativeFraction:frac(relative,o.relativeThreshold),packetCount:packets.length,longPackets:packets.filter(p=>p.duration>=6&&p.duration<=15).length,packetDuration:quantile(packets.map(p=>p.duration),.5),packetRate:packets.length/(count/1800),spacingMedian:quantile(packets.slice(1).map((p,i)=>(p.start-packets[i].start)/60),.5),riseMedian:quantile(packets.map(p=>p.rise),.5),fallMedian:quantile(packets.map(p=>p.fall),.5),carrier:carrierPeak(x),variants};
 const blocks=[];for(let b=edge;b+2700<=n-edge;b+=2700){let ok=true;for(let i=b;i<b+2700;i++)if(!valid[i]){ok=false;break}if(ok)blocks.push(b)}meta.blockCount=blocks.length;
 return{meta,packets,relativePackets,blocks,x,y,a,base,relative,valid,originalBad,leak:input.leak,pressure:input.pressure,epap:input.epap,flowLimit:input.flowLimit};
}
function detrend(x){const n=x.length,center=(n-1)/2,m=mean(x);let xy=0,xx=0;for(let i=0;i<n;i++){xy+=(i-center)*(x[i]-m);xx+=(i-center)**2}const slope=xx?xy/xx:0;return Float64Array.from(x,(v,i)=>v-m-slope*(i-center))}
function spectrum(x){const y=detrend(x),n=y.length;let ww=0;for(let i=0;i<n;i++){const w=.5-.5*Math.cos(2*Math.PI*i/n);y[i]*=w;ww+=w*w}const f=fft(y),power=new Float64Array(Math.floor(n/2)+1),freq=new Float64Array(power.length);for(let i=0;i<power.length;i++){freq[i]=i*FS/n;power[i]=(f.re[i]**2+f.im[i]**2)/(FS*ww)*(i&&!(n%2===0&&i===n/2)?2:1)}return{freq,power}}
function carrierPeak(x){const n=Math.min(x.length,2700);if(n<120)return null;let total=new Float64Array(Math.floor(n/2)+1),freq;for(let b=0;b+n<=x.length;b+=Math.floor(n/2)){const s=spectrum(x.subarray(b,b+n));freq=s.freq;for(let i=0;i<total.length;i++)total[i]+=s.power[i]}let best=-1;for(let i=1;i<total.length;i++)if(freq[i]>=1/120&&freq[i]<=1/20&&(best<0||total[i]>total[best]))best=i;return best>=0?1/freq[best]:null}
function acf(x,maxLag=750){const z=detrend(x),n=z.length;let m=1;while(m<2*n)m*=2;const re=new Float64Array(m);re.set(z);const im=new Float64Array(m);radix(re,im);for(let i=0;i<m;i++){re[i]=re[i]**2+im[i]**2;im[i]=0}radix(re,im,true);const out=re.slice(0,Math.min(maxLag+1,n)),norm=out[0];for(let i=0;i<out.length;i++)out[i]=norm>1e-20?out[i]/norm:0;return out}
function measures(y,smooth=120){const a=envelope(y,smooth).slice(90,-90),q10=quantile(a,.1),q90=quantile(a,.9),s=spectrum(a),c=acf(a);let slow=0;for(let i=0;i<s.freq.length;i++)if(s.freq[i]>=1/1800&&s.freq[i]<=1/180)slow+=s.power[i]*(FS/a.length);let best=150,found=false;for(let i=151;i<Math.min(750,c.length-1);i++)if(c[i]>c[i-1]&&c[i]>=c[i+1]&&(!found||c[i]>c[best])){best=i;found=true}if(!found)for(let i=150;i<Math.min(751,c.length);i++)if(c[i]>c[best])best=i;return{contrast:q90/Math.max(q10,1e-9),slowPower:slow/Math.max(mean(a)**2,1e-12),repeatPeak:c[best]||0,repeatLag:best/30,acf10:c[300]||0,cv:sd(a)/Math.max(mean(a),1e-9)}}
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function phase(y,random){const v=fft(y),n=y.length;for(let i=1;i<(n+1)/2;i++){const a=random()*2*Math.PI-Math.PI,c=Math.cos(a),s=Math.sin(a),r=v.re[i]*c-v.im[i]*s,im=v.re[i]*s+v.im[i]*c;v.re[i]=r;v.im[i]=im;v.re[n-i]=r;v.im[n-i]=-im}return fft(v.re,v.im,true).re}
function iaaft(y,random,iterations=100){const n=y.length,v=fft(y),target=Float64Array.from(v.re,(x,i)=>Math.hypot(x,v.im[i])),values=Float64Array.from(y).sort(),r=Float64Array.from(y),indices=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}let current=r;
 for(let k=0;k<iterations;k++){const f=fft(current);for(let i=0;i<n;i++){const mag=Math.hypot(f.re[i],f.im[i]);if(mag){f.re[i]*=target[i]/mag;f.im[i]*=target[i]/mag}else{f.re[i]=target[i];f.im[i]=0}}const z=fft(f.re,f.im,true).re;indices.sort((a,b)=>z[a]-z[b]||a-b);const next=new Float64Array(n);let same=true;for(let i=0;i<n;i++){next[indices[i]]=values[i];if(next[indices[i]]!==current[indices[i]])same=false}current=next;if(same)break}
 const f=fft(current);let num=0,den=0;for(let i=0;i<=n/2;i++){num+=(Math.hypot(f.re[i],f.im[i])-target[i])**2;den+=target[i]**2}return{signal:current,error:Math.sqrt(num/Math.max(den,1e-30))};
}
function bh(values){const order=values.map((v,i)=>i).sort((a,b)=>values[a]-values[b]),out=Array(values.length);let prev=1;for(let k=order.length-1;k>=0;k--){prev=Math.min(prev,values[order[k]]*values.length/(k+1));out[order[k]]=prev}return out}
function control(y,opts,method,count,seed,onProgress=()=>{}){const random=rng(seed),observed=measures(y,opts.smooth),keys=['contrast','slowPower','repeatPeak'],values=Object.fromEntries(keys.map(k=>[k,[]])),errors=[];for(let i=0;i<count;i++){const s=method==='iaaft'?iaaft(y,random):{signal:phase(y,random),error:0},m=measures(s.signal,opts.smooth);errors.push(s.error);for(const k of keys)values[k].push(m[k]);if(i%5===0)onProgress(i+1,count)}return{method,count,seed,observed,metrics:Object.fromEntries(keys.map(k=>[k,{observed:observed[k],median:quantile(values[k],.5),low:quantile(values[k],.025),high:quantile(values[k],.975),p:(1+values[k].filter(v=>v>=observed[k]).length)/(count+1)}])),spectralError:quantile(errors,.5)}}
function compact(result,bins=1200){const {x,a,base,valid,relative}=result,n=x.length,stride=Math.max(1,Math.ceil(n/bins)),out=[];for(let b=0;b<n;b+=stride){const e=Math.min(n,b+stride);let lo=Infinity,hi=-Infinity,am=0,ba=0,ok=0,rel=0,lk=0,pr=0,ep=0;for(let i=b;i<e;i++){lo=Math.min(lo,x[i]);hi=Math.max(hi,x[i]);am+=a[i];ba+=base[i];ok+=valid[i];rel+=relative[i];lk=Math.max(lk,result.leak?.[i]||0);pr+=result.pressure?.[i]||0;ep+=result.epap?.[i]||0}out.push([(b+e),lo,hi,am/(e-b),ba/(e-b),ok/(e-b),lk,pr/(e-b),ep/(e-b),rel/(e-b)])}return out}
function aggregate(sessions,gapHours=2){const sorted=[...sessions].sort((a,b)=>a.start-b.start),groups=[];for(const s of sorted){let g=groups.at(-1);if(!g||s.start-g.end>gapHours*3600000||s.start-g.start>18*3600000||s.source!==g.source){g={start:s.start,end:s.start+s.duration*1000,source:s.source,members:[]};groups.push(g)}g.members.push(s);g.end=Math.max(g.end,s.start+s.duration*1000)}return groups.map(g=>{const duration=sum(g.members.map(s=>s.duration)),usable=sum(g.members.map(s=>s.usableSeconds)),weight=k=>{let num=0,den=0;for(const s of g.members)if(Number.isFinite(s[k])){num+=s[k]*s.usableSeconds;den+=s.usableSeconds}return den?num/den:null},packets=g.members.flatMap(s=>(s.packets||[]).map(p=>({...p,start:s.start+p.start*1000,end:s.start+p.end*1000,peakTime:s.start+p.peakTime*1000,sessionId:s.id})));return{...g,id:g.members.map(s=>s.id).join('|'),duration,usableSeconds:usable,usableFraction:usable/duration,isNap:duration<10800,amplitude:weight('amplitude'),relativeAmplitude:weight('relativeAmplitude'),contrast:weight('contrast'),fraction:weight('fraction'),relativeFraction:weight('relativeFraction'),packetCount:sum(g.members.map(s=>s.packetCount)),longPackets:sum(g.members.map(s=>s.longPackets)),packetRate:sum(g.members.map(s=>s.packetCount))/(usable/3600),packetDuration:quantile(packets.map(p=>p.duration),.5),carrier:weight('carrier'),blockCount:sum(g.members.map(s=>s.blockCount)),packets,tag:[...new Set(g.members.map(s=>s.tag||s.support))].join(' / ')}})}
function trailing(groups,key){return groups.map(g=>{const day=Math.floor(g.start/86400000),members=groups.filter(v=>v.source===g.source&&Math.floor(v.start/86400000)>=day-6&&v.start<=g.start&&Number.isFinite(v[key]));return members.length?mean(members.map(v=>v[key])):null})}
function normalizeSettings(input={}){const o={...DEFAULTS};if(!input||typeof input!=='object')throw Error('Invalid saved settings');for(const key of ['band','source'])if(input[key]!==undefined)o[key]=input[key];if(!Object.hasOwn(SOS,o.band)||!['prefer','device','flow'].includes(o.source))throw Error('Invalid saved source or band');const ranges={smooth:[90,180],threshold:[.1,5],relativeThreshold:[.01,.8],minPacket:[60,900],bridge:[0,60],minSession:[30,120],trim:[300,300],leakLimit:[6,24],gap:[0,4],clockShift:[-24,24]};for(const [key,[lo,hi]] of Object.entries(ranges)){if(input[key]!==undefined){const value=input[key];if(typeof value!=='number'||!Number.isFinite(value)||value<lo||value>hi)throw Error('Invalid saved '+key);o[key]=value}}return o}
function validateSnapshot(data){if(!data||data.schema!=='wave-results'||data.version!==1||!Array.isArray(data.sessions)||data.sessions.length>10000)throw Error('Not a supported WAVE results file');const settings=normalizeSettings(data.settings),sessions=[];for(const s of data.sessions){if(!s||typeof s.id!=='string'||s.id.length>200||!Number.isFinite(s.start)||s.start<Date.UTC(1985,0,1)||s.start>Date.UTC(2100,0,1)||!Number.isFinite(s.duration)||s.duration<=0||s.duration>172800||!Number.isFinite(s.usableSeconds)||s.usableSeconds<=0||s.usableSeconds>s.duration+2||!Array.isArray(s.preview)||s.preview.length>2000||!Array.isArray(s.packets)||s.packets.length>10000||!['Device MV','Flow-derived'].includes(s.source))throw Error('Invalid saved session');for(const k of ['amplitude','relativeAmplitude','fraction','relativeFraction','packetCount','longPackets','contrast','blockCount'])if(!Number.isFinite(s[k])||s[k]<0)throw Error('Invalid saved metric');for(const p of s.preview)if(!Array.isArray(p)||p.length!==10||!p.every(Number.isFinite))throw Error('Invalid saved preview');for(const p of s.packets)if(!p||![p.start,p.end,p.duration,p.peak,p.rise,p.fall].every(Number.isFinite)||p.start<0||p.end> s.duration+2||p.end<p.start)throw Error('Invalid saved packet');const {_detail,...clean}=s;sessions.push({...clean,pairIndex:-1})}const annotations={};if(data.annotations&&typeof data.annotations==='object')for(const [key,value] of Object.entries(data.annotations)){if(['__proto__','prototype','constructor'].includes(key)||key.length>10000||!value)continue;annotations[key]={tag:String(value.tag||'').slice(0,60),note:String(value.note||'').slice(0,300)}}return{settings,sessions,annotations}}
return{VERSION,DEFAULTS,FS,SOS,clamp,sum,mean,quantile,sd,corr,select,rolling,filter,fft,envelope,runs,expandBad,packetize,parseEDF,at2s,flowMV,prepare,analyzeSignal,spectrum,carrierPeak,acf,measures,rng,phase,iaaft,bh,control,compact,aggregate,trailing,normalizeSettings,validateSnapshot};
})();
if(typeof module!=='undefined')module.exports=Wave;
