'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],W=Wave;
const state={queued:[],pairs:[],sessions:[],groups:[],visible:[],settings:{...W.DEFAULTS},processing:false,job:0,workers:new Set(),batch:null,detailWorker:null,nullWorker:null,selected:null,details:[],range:null,raw:[],controls:[],annotations:{},view:'longitudinal',scapePage:0,demo:false};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=2)=>Number.isFinite(v)?v.toFixed(d):'—',pct=v=>Number.isFinite(v)?`${(100*v).toFixed(1)}%`:'—';
const shift=()=>state.settings.clockShift*3600000,dateText=t=>new Date(t+shift()).toISOString().slice(0,10),clock=(t,seconds=false)=>new Date(t+shift()).toISOString().slice(11,seconds?19:16),timeText=t=>`${dateText(t)} ${clock(t,true)}`;
const colors={device:'#66d9ce',flow:'#ffb775',purple:'#b39aff',muted:'#91a3bc',line:'#293951',blue:'#72afff'};
function status(text,error=false){$('#status').classList.remove('ready');$('#status').textContent=text;$('#status').classList.toggle('error',error)}
function settings(){const o={...W.DEFAULTS};for(const k of ['source','band'])o[k]=$('#'+k).value;for(const k of ['smooth','threshold','relativeThreshold','minPacket','bridge','minSession','leakLimit','gap','clockShift']){const e=$('#'+k);if(!e.checkValidity())throw Error(`Check ${e.parentElement.textContent.trim()}`);o[k]=+e.value}o.relativeThreshold/=100;o.minPacket*=60;return o}
function showSettings(o){for(const k of Object.keys(W.DEFAULTS)){const e=$('#'+k);if(e)e.value=k==='relativeThreshold'?o[k]*100:k==='minPacket'?o[k]/60:o[k]}}
function makeWorker(){const source=$('#wave-engine').textContent+'\n'+$('#wave-worker').textContent,url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));let worker;try{worker=new Worker(url)}catch(e){URL.revokeObjectURL(url);throw Error('Background workers are unavailable in this browser. Open this file in a current Chrome or Edge browser.')}worker._url=url;state.workers.add(worker);return worker}
function stopWorker(worker){if(!worker)return;worker.terminate();URL.revokeObjectURL(worker._url);state.workers.delete(worker);if(worker._reject){worker._reject(Error('Cancelled'));worker._reject=null}}
function request(worker,data,progress=()=>{}){return new Promise((resolve,reject)=>{const id=++state.job;worker._reject=reject;worker.onmessage=({data:m})=>{if(m.id!==id)return;if(m.type==='progress'){progress(m);return}worker._reject=null;m.type==='error'?reject(Error(m.error)):resolve(m.result)};worker.onerror=e=>{worker._reject=null;reject(Error(e.message||'Background analysis failed'))};worker.postMessage({...data,id})})}
function fileKey(file){return`${file.webkitRelativePath||file.name}|${file.size}|${file.lastModified}`}
function filenameTime(f){const m=f.name.match(/^(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})/);return m?Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6]):null}
function pairFiles(files,o){const plds=files.filter(f=>/_PLD\.edf$/i.test(f.name)),brps=files.filter(f=>/_BRP\.edf$/i.test(f.name)),used=new Set(),pairs=[];const directory=f=>(f.webkitRelativePath||'').split('/').slice(0,-1).join('/');for(const pld of plds){const t=filenameTime(pld),matches=brps.map((b,i)=>({b,i,dist:t===null?Infinity:Math.abs(filenameTime(b)-t)})).filter(x=>x.dist<=2000&&!used.has(x.i)&&(!directory(pld)||!directory(x.b)||directory(pld)===directory(x.b))).sort((a,b)=>a.dist-b.dist);let brp=null;if(matches.length){brp=matches[0].b;used.add(matches[0].i)}if(o.source==='flow'&&!brp)continue;pairs.push({pld,brp,name:pld.name,startHint:t})}if(o.source!=='device')for(let i=0;i<brps.length;i++)if(!used.has(i))pairs.push({pld:null,brp:brps[i],name:brps[i].name,startHint:filenameTime(brps[i])});return pairs.sort((a,b)=>(a.startHint||0)-(b.startHint||0))}
function issues(lines){$('#issues').hidden=!lines.length;$('#issueSummary').textContent=`Import details · ${lines.length} skipped or failed`;$('#issueList').replaceChildren(...lines.map(t=>{const li=document.createElement('li');li.textContent=t;return li}))}
async function processAll(){if(state.processing||!state.queued.length)return;let opts;try{opts=settings()}catch(e){status(e.message,true);return}cancelDetails();cancelNull();state.settings=opts;state.sessions=[];state.controls=[];state.annotations={};state.demo=false;state.pairs=pairFiles(state.queued,opts);const jobs=state.pairs,seen=new Set(),errors=[];state.processing=true;$('#process').disabled=true;$('#cancel').hidden=false;$('#progress').hidden=false;$('#progress').value=0;$('#results').hidden=true;$('#night').hidden=true;$('#settingsBadge').textContent='Settings applied to this run';let worker,complete=0;const began=Date.now(),timer=setInterval(()=>{$('#cancel').textContent=`Cancel · ${Math.round((Date.now()-began)/1000)}s`},1000);
 try{worker=makeWorker();state.batch=worker;for(let i=0;i<jobs.length;i++){if(!state.processing)break;status(`Analyzing ${i+1}/${jobs.length}: ${jobs[i].name}`);try{const r=await request(worker,{kind:'analyze',pair:jobs[i],settings:opts});if(r.skipped){errors.push(`${jobs[i].name}: ${r.skipped}`)}else if(seen.has(r.hash)){errors.push(`${jobs[i].name}: duplicate data`)}else if(state.sessions.some(s=>s.source===r.source&&r.start<s.start+s.duration*1000-2000&&r.start+r.duration*1000>s.start+2000)){errors.push(`${jobs[i].name}: overlaps another accepted recording; excluded to avoid counting time twice`)}else{seen.add(r.hash);const id=r.hash;state.sessions.push({...r,id,pairIndex:i,filename:jobs[i].name});}complete++;$('#progress').value=100*(i+1)/jobs.length;if(i%5===0&&state.sessions.length)renderResults(false)}catch(e){if(!state.processing)break;errors.push(`${jobs[i].name}: ${e.message}`);complete++;}}}catch(e){errors.push(e.message)}finally{clearInterval(timer);stopWorker(worker);state.batch=null;const cancelled=!state.processing;state.processing=false;$('#cancel').hidden=true;$('#process').disabled=!state.queued.length;$('#process').textContent='Reprocess selected';issues(errors);renderResults(true);status(`${cancelled?'Stopped':'Complete'}: ${state.sessions.length} usable sessions from ${complete}/${jobs.length} session candidates · ${Math.round((Date.now()-began)/1000)}s. ${errors.length} skipped/failed.${cancelled?' Completed results are retained.':''}`,!state.sessions.length)}}
function cancelBatch(){state.processing=false;stopWorker(state.batch);state.batch=null}
function rebuild(){state.groups=W.aggregate(state.sessions,state.settings.gap);for(const g of state.groups){const note=state.annotations[g.id];if(note){g.tag=note.tag||g.tag;g.note=note.note||''}}}
function filtered(){const from=$('#dateFrom').value,to=$('#dateTo').value,source=$('#sourceFilter').value,type=$('#typeFilter').value;return state.groups.filter(g=>(!from||dateText(g.start)>=from)&&(!to||dateText(g.start)<=to)&&(source==='all'||g.source===source)&&(type==='all'||g.isNap===(type==='nap')))}
function renderResults(initialize=false){rebuild();if(initialize&&state.groups.length){const dates=state.groups.map(g=>dateText(g.start)),first=dates[0],last=dates.at(-1);$('#dateFrom').value=first;$('#dateTo').value=last;$('#aFrom').value=first;$('#aTo').value=dates[Math.max(0,Math.floor(dates.length*.75)-1)];$('#bFrom').value=dates[Math.floor(dates.length*.75)];$('#bTo').value=last}$('#results').hidden=!state.groups.length;state.visible=filtered();renderSummary();renderTrends();renderTable();if(state.view==='scape')renderScape();}
function renderSummary(){const g=state.visible,median=k=>W.quantile(g.map(x=>x[k]).filter(Number.isFinite),.5);const items=[[String(g.length),'RECORDING PERIODS',`${g.filter(x=>!x.isNap).length} nights · ${g.filter(x=>x.isNap).length} naps`],[fmt(W.sum(g.map(x=>x.usableSeconds))/3600,1),'USABLE HOURS','Recording time, not scored sleep'],[fmt(median('amplitude'),3),'MEDIAN ENVELOPE · L/MIN','Median of displayed period values'],[pct(median('fraction')),'TIME ABOVE THRESHOLD',`${state.settings.threshold} L/min · median period`],[fmt(median('longPackets'),0),'6–15 MIN PACKETS','Median count per period']];$('#summary').innerHTML=items.map(([v,l,s])=>`<div class="metric"><b>${v}</b><span>${l}</span><small>${s}</small></div>`).join('');if(new Set(g.map(x=>x.source)).size>1)$('#summary').insertAdjacentHTML('beforeend','<p class="hint" style="grid-column:1/-1">Summary includes both source types. Filter to one source for amplitude comparisons; smoothed trends remain separate.</p>')}
function setupCanvas(canvas,height){const width=Math.max(220,canvas.clientWidth||canvas.parentElement.clientWidth||800),dpr=Math.min(devicePixelRatio||1,2);canvas.style.height=height+'px';canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#0b1626';ctx.fillRect(0,0,width,height);ctx.font='11px system-ui';return{ctx,width,height}}
function grid(ctx,width,height,p,max,min=0){ctx.strokeStyle='#24344a';ctx.fillStyle='#90a1b8';ctx.lineWidth=1;for(let i=0;i<=3;i++){const y=p.top+(height-p.top-p.bottom)*i/3;ctx.beginPath();ctx.moveTo(p.left,y);ctx.lineTo(width-p.right,y);ctx.stroke();ctx.fillText(fmt(max-(max-min)*i/3,max<3?2:0),7,y+4)}}
// Calendar-distance weighting: centered display smoothing, independent of analysis.
function trendSmooth(data,key,days){
 const result=new Array(data.length).fill(null),day=86400000,radius=days*day/2,sigma=radius/2;
 for(const source of ['Device MV','Flow-derived']){
  const points=data.map((g,i)=>({g,i})).filter(p=>p.g.source===source&&Number.isFinite(p.g[key]));
  const segments=[];for(const p of points){if(!segments.length||p.g.start-segments.at(-1).at(-1).g.start>10*day)segments.push([]);segments.at(-1).push(p)}
  for(const segment of segments)for(const p of segment){let total=0,weight=0;for(const q of segment){const dt=q.g.start-p.g.start;if(Math.abs(dt)>radius)continue;const w=Math.exp(-.5*(dt/sigma)**2);total+=q.g[key]*w;weight+=w}result[p.i]=total/weight}
 }
 return result;
}
// Monotone cubic interpolation keeps the visual curve within neighboring values.
function trendPath(ctx,points){
 if(!points.length)return;ctx.moveTo(points[0].x,points[0].y);
 const slopes=points.slice(1).map((p,i)=>(p.y-points[i].y)/(p.x-points[i].x||1));
 const tangent=points.map((p,i)=>{if(i===0)return slopes[0]||0;if(i===points.length-1)return slopes.at(-1)||0;const a=slopes[i-1],b=slopes[i];return a*b<=0?0:2*a*b/(a+b)});
 for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=(b.x-a.x)/3;ctx.bezierCurveTo(a.x+dx,a.y+dx*tangent[i-1],b.x-dx,b.y-dx*tangent[i],b.x,b.y)}
}
const chartSpecs=[['amplitude','Wave strength','Envelope in L/min','L/min',1],['fraction','Time with strong waves','Fraction above the chosen absolute threshold','%',100],['relativeAmplitude','Relative wave strength','Envelope / local average ventilation','%',100],['packetDuration','Packet duration','Median complete candidate duration','min',1],['longPackets','Sustained packets','Candidates lasting 6–15 minutes','packets',1]];
function renderTrends(){
 const host=$('#trendCharts');if(!host.childElementCount)for(const [key,title,description] of chartSpecs){const d=document.createElement('div');d.className='chart';d.innerHTML=`<h3>${title}</h3><p>${description}</p><canvas id="trend-${key}" role="img" aria-label="${title} over time"></canvas><div class="tooltip" hidden></div>`;host.append(d)}
 if(state.view!=='longitudinal')return;const days=+$('#trendSmooth').value;
 for(const label of $$('.trend-legend [data-source]'))label.hidden=!state.visible.some(g=>g.source===label.dataset.source&&chartSpecs.some(([key])=>Number.isFinite(g[key])));
 for(const [key,title,desc,unit,mult] of chartSpecs){
  const canvas=$('#trend-'+key),{ctx,width,height}=setupCanvas(canvas,key==='amplitude'?270:240),data=state.visible.filter(g=>Number.isFinite(g[key])),tip=canvas.parentElement.querySelector('.tooltip');tip.hidden=true;
  if(!data.length){ctx.fillStyle=colors.muted;ctx.fillText('No periods in this date range',45,100);canvas.onclick=null;canvas.onpointermove=null;continue}
  const smoothed=trendSmooth(data,key,days),p={left:48,right:24,top:22,bottom:34},lo=data[0].start,hi=data.at(-1).start,span=Math.max(86400000,hi-lo),max=Math.max(.01,...data.map(g=>g[key]*mult))*1.15,x=t=>p.left+(t-lo)/span*(width-p.left-p.right),y=v=>height-p.bottom-v*mult/max*(height-p.top-p.bottom);
  ctx.globalAlpha=.48;grid(ctx,width,height,p,max);ctx.globalAlpha=1;
  for(const source of ['Device MV','Flow-derived']){
   const points=data.map((g,i)=>({g,i})).filter(v=>v.g.source===source),color=source==='Device MV'?colors.device:colors.flow;
   ctx.fillStyle=color;ctx.globalAlpha=.22;
   for(const {g} of points){const xx=x(g.start),yy=y(g[key]);ctx.beginPath();if(source==='Device MV')ctx.arc(xx,yy,2.8,0,Math.PI*2);else{ctx.moveTo(xx,yy-3.5);ctx.lineTo(xx+3.5,yy);ctx.lineTo(xx,yy+3.5);ctx.lineTo(xx-3.5,yy);ctx.closePath()}ctx.fill()}
   const segments=[];for(const {g,i} of points){if(!segments.length||g.start-segments.at(-1).at(-1).time>10*86400000)segments.push([]);segments.at(-1).push({x:x(g.start),y:y(smoothed[i]),time:g.start})}
   ctx.strokeStyle=color;ctx.lineCap='round';ctx.lineJoin='round';
   for(const [alpha,lineWidth] of [[.065,9],[.95,2.6]]){ctx.globalAlpha=alpha;ctx.lineWidth=lineWidth;ctx.beginPath();for(const segment of segments)trendPath(ctx,segment);ctx.stroke()}
   ctx.globalAlpha=.8;for(const segment of segments)if(segment.length===1){ctx.beginPath();ctx.arc(segment[0].x,segment[0].y,2.3,0,Math.PI*2);ctx.fill()}
  }
  ctx.globalAlpha=1;ctx.fillStyle=colors.muted;for(let i=0;i<4;i++){const t=lo+span*i/3;ctx.fillText(span>300*86400000?dateText(t):dateText(t).slice(5),W.clamp(x(t)-15,40,width-(span>300*86400000?75:40)),height-9)}
  const nearest=event=>{const rect=canvas.getBoundingClientRect(),px=event.clientX-rect.left,py=event.clientY-rect.top;return data.map((g,i)=>({g,i,dist:Math.hypot(x(g.start)-px,y(g[key])-py)})).sort((a,b)=>a.dist-b.dist)[0]};
  canvas.onpointermove=e=>{const n=nearest(e);tip.innerHTML=`<b>${esc(timeText(n.g.start))}</b><br>${esc(n.g.source)} · ${n.g.isNap?'Nap':'Night'} · ${fmt(n.g.duration/3600,1)} h<br>${esc(title)}: ${fmt(n.g[key]*mult)} ${unit}<br>Centered ${days}-day trend: ${fmt(smoothed[n.i]*mult)} ${unit}`;tip.hidden=false;tip.style.left=W.clamp(e.clientX-canvas.getBoundingClientRect().left+10,0,width-245)+'px';tip.style.top='45px'};
  canvas.onpointerleave=()=>tip.hidden=true;canvas.onclick=e=>openNight(nearest(e).g.id);
 }
}

function renderTable(){const groups=[...state.visible].reverse(),months=new Map();for(const g of groups){const month=dateText(g.start).slice(0,7);if(!months.has(month))months.set(month,[]);months.get(month).push(g)}const host=$('#periodTable');host.replaceChildren();let j=0;for(const [month,list] of months){const d=document.createElement('details');d.className='month';d.open=j++===0;d.innerHTML=`<summary>${month} <span class="hint">· ${list.length} periods</span></summary><table><thead><tr><th>Device date / time</th><th>Source / label</th><th>Sessions</th><th>Usable h</th><th>Retained</th><th>Envelope</th><th>Strong time</th><th>6–15 min</th></tr></thead><tbody>${list.map(g=>`<tr><td><button class="link period-link" data-id="${esc(g.id)}">${timeText(g.start)}</button>${g.isNap?'<span class="badge">Nap</span>':''}</td><td>${esc(g.source)}<br><span class="hint">${esc(g.tag)}</span></td><td>${g.members.length}</td><td class="num">${fmt(g.usableSeconds/3600)}</td><td class="num">${pct(g.usableFraction)}</td><td class="num">${fmt(g.amplitude,3)}</td><td class="num">${pct(g.fraction)}</td><td class="num">${g.longPackets}</td></tr>`).join('')}</tbody></table>`;host.append(d)}host.querySelectorAll('.period-link').forEach(b=>b.onclick=()=>openNight(b.dataset.id))}
function scapeColor(v,relative){const t=W.clamp(v/(relative?.22:1.2),0,1),stops=[[15,24,42],[62,42,98],[131,82,179],[215,131,172],[255,223,147]],a=Math.min(3,Math.floor(t*4)),f=t*4-a;return`rgb(${stops[a].map((x,i)=>Math.round(x+(stops[a+1][i]-x)*f)).join(',')})`}
function renderScape(){const g=state.visible,perPage=100,maxPage=Math.max(0,Math.ceil(g.length/perPage)-1);state.scapePage=W.clamp(state.scapePage,0,maxPage);const rows=g.slice(state.scapePage*perPage,(state.scapePage+1)*perPage),relative=$('#scapeMode').value==='relative',canvas=$('#scapeCanvas'),{ctx,width,height}=setupCanvas(canvas,Math.max(230,rows.length*18+60)),left=145,right=24,top=30,rowHeight=(height-60)/Math.max(rows.length,1),span=Math.max(6,...rows.map(g=>(g.end-g.start)/3600000)),x=h=>left+h/span*(width-left-right);ctx.fillStyle=colors.muted;for(let h=0;h<=span;h+=2)ctx.fillText(h+'h',x(h)-5,18);rows.forEach((g,j)=>{const y=top+j*rowHeight;ctx.fillStyle=colors.muted;ctx.fillText(dateText(g.start)+(g.isNap?' · nap':''),8,y+12);for(const s of g.members){const points=s.preview||[],bin=s.duration/Math.max(points.length,1);for(const p of points){const h=(s.start-g.start)/3600000+(p[0]-bin/2)/3600;ctx.fillStyle=p[5]<.99?'#394456':scapeColor(relative?p[9]:p[3],relative);ctx.fillRect(x(h),y,Math.max(.6,bin/3600/span*(width-left-right)+.2),rowHeight-2)}}});$('#scapeTip').innerHTML=`${rows.length?state.scapePage*perPage+1:0}–${Math.min((state.scapePage+1)*perPage,g.length)} of ${g.length} periods · ${relative?'0–22%':'0–1.2 L/min'} color scale · gray = excluded/mixed quality <button id="scapePrev" class="quiet">←</button> <button id="scapeNext" class="quiet">→</button>`;$('#scapePrev').disabled=state.scapePage===0;$('#scapeNext').disabled=state.scapePage===maxPage;$('#scapePrev').onclick=()=>{state.scapePage--;renderScape()};$('#scapeNext').onclick=()=>{state.scapePage++;renderScape()};canvas.onclick=e=>{const y=e.clientY-canvas.getBoundingClientRect().top,index=Math.floor((y-top)/rowHeight);if(rows[index])openNight(rows[index].id)}}
function compare(){const source=$('#compareSource').value,range=(from,to)=>state.groups.filter(g=>g.source===source&&dateText(g.start)>=from&&dateText(g.start)<=to),a=range($('#aFrom').value,$('#aTo').value);let b=range($('#bFrom').value,$('#bTo').value);const overlap=a.filter(g=>b.some(h=>h.id===g.id));if(overlap.length){$('#comparison').textContent='Choose nonoverlapping date ranges.';return}const count=$('#sampleCount').value;if(count!=='all'){const random=W.rng(+$('#compareSeed').value);b=[...b];for(let i=b.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}b=b.slice(0,+count).sort((x,y)=>x.start-y.start)}if(!a.length||!b.length){$('#comparison').textContent='Both ranges need at least one period for this ventilation source.';return}const m=(g,k)=>W.quantile(g.map(x=>x[k]).filter(Number.isFinite),.5);$('#comparison').innerHTML=`<table><thead><tr><th>Median across periods</th><th>Range A · ${a.length}</th><th>Range B · ${b.length}</th></tr></thead><tbody>${[['amplitude','Envelope (L/min)',1],['relativeAmplitude','Relative envelope (%)',100],['fraction','Time above absolute threshold (%)',100],['relativeFraction','Time above relative threshold (%)',100],['packetRate','Candidate packets / usable hour',1],['packetDuration','Candidate duration (min)',1],['longPackets','6–15 min packets per period',1]].map(([k,l,mult])=>`<tr><td>${l}</td><td>${fmt(Number.isFinite(m(a,k))?m(a,k)*mult:null)}</td><td>${fmt(Number.isFinite(m(b,k))?m(b,k)*mult:null)}</td></tr>`).join('')}</tbody></table><p class="hint">Source: ${esc(source)} · Usable hours A ${fmt(W.sum(a.map(g=>g.usableSeconds))/3600,1)}, B ${fmt(W.sum(b.map(g=>g.usableSeconds))/3600,1)}. B selections: ${b.map(g=>esc(dateText(g.start))).join(', ')}.</p>`}
function cancelDetails(){if(state.detailWorker)stopWorker(state.detailWorker);if(state.rawWorker)stopWorker(state.rawWorker);state.rawWorker=null;state.rawToken=(state.rawToken||0)+1;state.detailWorker=null;state.detailToken=(state.detailToken||0)+1;state.details=[];state.raw=[]}
async function openNight(id){const group=state.groups.find(g=>g.id===id);if(!group)return;cancelDetails();const token=state.detailToken;state.selected=group;$('#night').hidden=false;$('#nightKind').textContent=group.isNap?'NAP / RECORDED PERIOD':'NIGHT / RECORDED PERIOD';$('#nightTitle').textContent=timeText(group.start);$('#nightMeta').textContent=`${group.members.length} session(s) · ${fmt(group.usableSeconds/3600,2)} usable hours · ${group.source} · ${group.tag}${group.members.every(s=>!s.hasLeak)?' · Leak screening unavailable (no PLD leak channel)':''}`;$('#nightTag').value=state.annotations[id]?.tag||'';$('#nightNote').value=state.annotations[id]?.note||'';state.range={from:group.start,to:Math.min(group.end,group.start+90*60000)};$('#night').scrollIntoView({behavior:'smooth',block:'start'});renderPackets();drawOverview();drawDetail();$('#sensitivity').textContent='Loading sensitivity checks…';$('#rawStatus').textContent='Open this section to read matching raw airflow.';if(state.demo){state.details=group.members.map(s=>({...s,...s._detail}));$('#detailStatus').textContent='Synthetic example. Not a real recording.';drawOverview();drawDetail();renderSensitivity();return}if(!group.members.some(s=>state.pairs[s.pairIndex])){$('#detailStatus').textContent='Saved summary only. Select and process the original EDF files to enable full-resolution inspection.';$('#sensitivity').textContent='Source files required.';return}
 let worker;try{worker=makeWorker();state.detailWorker=worker;for(let i=0;i<group.members.length;i++){if(token!==state.detailToken)return;const s=group.members[i],pair=state.pairs[s.pairIndex];if(!pair)continue;$('#detailStatus').textContent=`Reading session ${i+1}/${group.members.length} and checking alternate filters…`;const r=await request(worker,{kind:'detail',pair,settings:state.settings});if(token!==state.detailToken)return;if(!r.skipped)state.details.push({...r,id:s.id,pairIndex:s.pairIndex});}$('#detailStatus').textContent='Ready. Drag to select an interval; click the detail plot to zoom around a point.';drawOverview();drawDetail();renderSensitivity();if($('#rawSection').open)loadRaw()}catch(e){if(token===state.detailToken)$('#detailStatus').textContent=e.message}finally{stopWorker(worker);if(state.detailWorker===worker)state.detailWorker=null}}
function timeAxis(ctx,width,height,p,from,to){ctx.fillStyle=colors.muted;for(let i=0;i<5;i++){const t=from+(to-from)*i/4;ctx.fillText(clock(t,to-from<10*60000),W.clamp(p.left+(width-p.left-p.right)*i/4-18,p.left,width-65),height-7)}}
function bindSelection(canvas,from,to,onSelect,clickZoom=true){let anchor=null;const position=e=>{const r=canvas.getBoundingClientRect(),p=canvas._plot;return W.clamp((e.clientX-r.left-p.left)/(r.width-p.left-p.right),0,1)*(to-from)+from};canvas.onpointerdown=e=>{anchor={t:position(e),x:e.clientX};canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=e=>{if(!anchor)return;const t=position(e),a=anchor;anchor=null;if(Math.abs(e.clientX-a.x)<4){if(clickZoom){const span=Math.max(5000,(to-from)/2);onSelect(t-span/2,t+span/2)}}else onSelect(Math.min(a.t,t),Math.max(a.t,t))};canvas.onpointercancel=()=>anchor=null}
function setRange(from,to){const g=state.selected;if(!g)return;const span=W.clamp(to-from,5000,g.end-g.start);from=W.clamp(from,g.start,Math.max(g.start,g.end-span));state.range={from,to:from+span};drawOverview();drawDetail();if($('#rawSection').open)loadRaw()}
function drawOverview(){const g=state.selected;if(!g)return;const c=$('#overview'),{ctx,width,height}=setupCanvas(c,225),p={left:54,right:20,top:20,bottom:30},span=g.end-g.start,x=t=>p.left+(t-g.start)/span*(width-p.left-p.right),max=Math.max(1.2,...g.members.flatMap(s=>(s.preview||[]).map(p=>p[3]))),y=v=>height-p.bottom-v/max*(height-p.top-p.bottom);grid(ctx,width,height,p,max);for(const s of g.members){const pts=s.preview||[];ctx.beginPath();ctx.strokeStyle=colors.purple;ctx.lineWidth=1.1;pts.forEach((point,i)=>{const xx=x(s.start+point[0]*1000),yy=y(point[3]);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();const step=s.duration/Math.max(pts.length,1);for(const point of pts)if(point[5]<.99){ctx.fillStyle='#94a3b829';ctx.fillRect(x(s.start+(point[0]-step/2)*1000),p.top,Math.max(1,step*1000/span*(width-p.left-p.right)),height-p.top-p.bottom)}ctx.strokeStyle=colors.line;ctx.beginPath();ctx.moveTo(x(s.start),p.top);ctx.lineTo(x(s.start),height-p.bottom);ctx.stroke()}ctx.strokeStyle='#73819d';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(p.left,y(state.settings.threshold));ctx.lineTo(width-p.right,y(state.settings.threshold));ctx.stroke();ctx.setLineDash([]);if(state.range){ctx.fillStyle='#a78bfa20';ctx.fillRect(x(state.range.from),p.top,x(state.range.to)-x(state.range.from),height-p.top-p.bottom);ctx.strokeStyle=colors.purple;ctx.strokeRect(x(state.range.from),p.top,x(state.range.to)-x(state.range.from),height-p.top-p.bottom)}timeAxis(ctx,width,height,p,g.start,g.end);c._plot=p;bindSelection(c,g.start,g.end,setRange)}
function drawDetail(){const g=state.selected,range=state.range;if(!g||!range)return;const c=$('#detailCanvas'),{ctx,width,height}=setupCanvas(c,690),p={left:61,right:20,top:25,bottom:30},span=range.to-range.from,x=t=>p.left+(t-range.from)/span*(width-p.left-p.right),panelHeight=140;$('#rangeText').textContent=`${timeText(range.from)} — ${timeText(range.to)} · ${fmt(span/60000,2)} minutes · original device clock${shift()?` adjusted ${state.settings.clockShift}h for display`:''}`;const specs=[['Minute ventilation · L/min','x',15,colors.device],['Wave envelope · L/min','a',2.1,colors.purple],['Leak · L/min','leak',30,colors.flow],['Pressure · cmH₂O','pressure',20,colors.flow]];
 for(let j=0;j<specs.length;j++){const [label,key,floor,color]=specs[j],top=27+j*165,bottom=top+panelHeight,max=Math.max(floor,...state.details.flatMap(s=>{const arr=s[key];if(!arr)return[];const lo=W.clamp(Math.floor((range.from-s.start)/2000),0,arr.length),hi=W.clamp(Math.ceil((range.to-s.start)/2000),0,arr.length);let m=0;for(let i=lo;i<hi;i++)if(Number.isFinite(arr[i]))m=Math.max(m,arr[i]);return[m]})),y=v=>bottom-v/max*panelHeight;ctx.fillStyle='#d4e1f4';ctx.font='bold 12px system-ui';ctx.fillText(label,p.left,top-9);ctx.font='11px system-ui';for(let k=0;k<=2;k++){const value=max*k/2;ctx.strokeStyle=colors.line;ctx.beginPath();ctx.moveTo(p.left,y(value));ctx.lineTo(width-p.right,y(value));ctx.stroke();ctx.fillStyle=colors.muted;ctx.fillText(fmt(value,max<3?1:0),10,y(value)+3)}
 for(const s of state.details){const n=s.x.length,lo=W.clamp(Math.floor((range.from-s.start)/2000),0,n),hi=W.clamp(Math.ceil((range.to-s.start)/2000),0,n),stride=Math.max(1,Math.ceil((hi-lo)/(width-p.left-p.right)));for(let b=lo;b<hi;b+=stride){let bad=false;for(let i=b;i<Math.min(hi,b+stride);i++)if(!s.valid[i])bad=true;if(bad){ctx.fillStyle='#94a3b820';ctx.fillRect(x(s.start+b*2000),top,Math.max(1,stride*2000/span*(width-p.left-p.right)),panelHeight)}}const line=(arr,col,minmax=false)=>{if(!arr)return;ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();let begun=false;for(let b=lo;b<hi;b+=stride){let sum=0,count=0,low=Infinity,high=-Infinity;for(let i=b;i<Math.min(hi,b+stride);i++)if(Number.isFinite(arr[i])){sum+=arr[i];count++;low=Math.min(low,arr[i]);high=Math.max(high,arr[i])}if(!count){begun=false;continue}const xx=x(s.start+b*2000),yy=y(sum/count);if(minmax){ctx.moveTo(xx,y(low));ctx.lineTo(xx,y(high))}else{begun?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);begun=true}}ctx.stroke()};line(s[key],color,key==='x');if(key==='x')line(s.base,'#d5dcec');if(key==='a'){line(s.flowEnvelope,colors.device);ctx.strokeStyle='#8992aa';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(p.left,y(state.settings.threshold));ctx.lineTo(width-p.right,y(state.settings.threshold));ctx.stroke();ctx.setLineDash([])}if(key==='pressure')line(s.epap,colors.muted)}
 if(!state.details.length){ctx.fillStyle=colors.muted;ctx.fillText('Full-resolution data will appear after source files are read.',p.left,top+60)}ctx.fillStyle=colors.muted;for(let i=0;i<5;i++)ctx.fillText(clock(range.from+span*i/4,span<600000),p.left+(width-p.left-p.right)*i/4-12,bottom+17)}c._plot=p;bindSelection(c,range.from,range.to,setRange);$('#previous').disabled=range.from<=g.start;$('#next').disabled=range.to>=g.end;$('#zoomIn').disabled=span<=5000;$('#zoomOut').disabled=span>=g.end-g.start;}
function renderPackets(){const g=state.selected;if(!g)return;const packets=g.packets||[];$('#packetTable').innerHTML=packets.length?`<table><thead><tr><th>Start</th><th>Minutes</th><th>Peak L/min</th><th>Rise min</th><th>Fall min</th></tr></thead><tbody>${packets.slice(0,300).map((p,i)=>`<tr><td><button class="link packet" data-index="${i}">${timeText(p.start)}</button></td><td>${fmt(p.duration)}</td><td>${fmt(p.peak)}</td><td>${fmt(p.rise)}</td><td>${fmt(p.fall)}</td></tr>`).join('')}</tbody></table>`:'<p class="hint">No complete packets at the current threshold.</p>';$('#packetTable').querySelectorAll('.packet').forEach(b=>b.onclick=()=>{const p=packets[+b.dataset.index];setRange(p.start-120000,p.end+120000)})}
function renderSensitivity(){const details=state.details;if(!details.length)return;const rows=new Map();for(const d of details)for(const r of d.variants||[]){if(!rows.has(r.name))rows.set(r.name,[]);rows.get(r.name).push(r)}const table=[...rows].map(([name,rr])=>{const seconds=W.sum(rr.map(r=>r.seconds));return`<tr><td>${esc(name)}</td><td>${pct(seconds?W.sum(rr.map(r=>r.fraction*r.seconds))/seconds:null)}</td><td>${fmt(seconds/3600)}</td><td>${fmt(W.quantile(rr.map(r=>r.correlation).filter(Number.isFinite),.5),3)}</td></tr>`}).join('');const thresholds=details[0]?.thresholds||[];const thresholdTable='<h3 style="margin-top:20px">Threshold sensitivity</h3><table><thead><tr><th>Definition</th><th>Above threshold</th><th>Packets</th><th>6–15 min</th></tr></thead><tbody>'+thresholds.map((t,i)=>{const rr=details.filter(d=>d.thresholds?.[i]),seconds=W.sum(rr.map(d=>d.usableSeconds));return `<tr><td>${esc(t.label)}</td><td>${pct(seconds?W.sum(rr.map(d=>d.thresholds[i].fraction*d.usableSeconds))/seconds:null)}</td><td>${W.sum(rr.map(d=>d.thresholds[i].packets))}</td><td>${W.sum(rr.map(d=>d.thresholds[i].longPackets))}</td></tr>`}).join('')+'</tbody></table>';$('#sensitivity').innerHTML=`<p class="hint">Fraction above ${state.settings.threshold} L/min; retained time changes with each quality mask.</p><table><thead><tr><th>Check</th><th>Above threshold</th><th>Usable h</th><th>Envelope r</th></tr></thead><tbody>${table}</tbody></table>${thresholdTable}<h3 style="margin-top:20px">Airflow agreement</h3>${details.map(d=>`<p class="hint">${esc(timeText(d.start))}: ${d.flowCheck?.error?esc(d.flowCheck.error):d.flowCheck?`r = ${fmt(d.flowCheck.r,3)} · airflow minus PLD clock ${d.flowCheck.offsetSeconds}s`:'No paired airflow comparison available.'}</p>`).join('')}<p class="hint">Both channels originate from the PAP sensor. Airflow-derived amplitude can be systematically higher; this is a timing cross-check, not an independent physiological measurement.</p>`}
async function loadRaw(){const range=state.range,g=state.selected;if(!range||!g)return;state.rawToken=(state.rawToken||0)+1;const token=state.rawToken;if(state.rawWorker)stopWorker(state.rawWorker);state.raw=[];let worker;try{const candidates=g.members.filter(s=>state.pairs[s.pairIndex]?.brp&&s.start<range.to&&s.start+s.duration*1000>range.from);if(!candidates.length){$('#rawStatus').textContent=state.demo?'Raw airflow is not included in the synthetic demo.':'Select matching BRP files to enable individual-breath detail.';drawRaw();return}worker=makeWorker();state.rawWorker=worker;$('#rawStatus').textContent='Reading calibrated airflow…';for(const s of candidates){const r=await request(worker,{kind:'raw',pair:state.pairs[s.pairIndex],from:range.from,to:range.to});if(token!==state.rawToken)return;state.raw.push(r)}$('#rawStatus').textContent='Calibrated flow in L/min. Min–max bins preserve excursions. Drag to zoom; click to halve the window.';drawRaw()}catch(e){if(token===state.rawToken)$('#rawStatus').textContent=e.message}finally{stopWorker(worker);if(state.rawWorker===worker)state.rawWorker=null}}
function drawRaw(){const r=state.range;if(!r)return;const c=$('#rawCanvas'),{ctx,width,height}=setupCanvas(c,260),p={left:55,right:20,top:20,bottom:30},points=state.raw.flatMap(s=>s.points),max=Math.max(30,...points.map(p=>Math.max(Math.abs(p[1]),Math.abs(p[2])))),x=t=>p.left+(t-r.from)/(r.to-r.from)*(width-p.left-p.right),y=v=>p.top+(max-v)/(2*max)*(height-p.top-p.bottom);grid(ctx,width,height,p,max,-max);ctx.strokeStyle=colors.device;ctx.lineWidth=.7;ctx.beginPath();for(const [t,lo,hi] of points){ctx.moveTo(x(t),y(lo));ctx.lineTo(x(t),y(hi))}ctx.stroke();for(const s of state.raw){ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(x(p[0]),y(p[3])):ctx.moveTo(x(p[0]),y(p[3])));ctx.stroke()}timeAxis(ctx,width,height,p,r.from,r.to);c._plot=p;bindSelection(c,r.from,r.to,setRange)}
function cancelNull(){if(state.nullWorker)stopWorker(state.nullWorker);state.nullWorker=null;state.nullRunning=false;$('#cancelNull').hidden=true;$('#runNull').disabled=false}
async function runNull(){if(state.nullRunning)return;if(state.demo){$('#nullStatus').textContent='Process real EDF files to run controls.';return}
 const groups=($('#nullScope').value==='selected'?[state.selected]:state.visible).filter(Boolean),eligible=groups.filter(g=>g.members.some(s=>s.blockCount&&state.pairs[s.pairIndex]));
 if(!eligible.length){$('#nullStatus').textContent='No eligible 90-minute blocks with available source files.';return}
 const seed=+$('#nullSeed').value,count=+$('#nullCount').value,method=$('#nullMethod').value,methods=method==='both'?['phase','iaaft']:[method],tasks=[];
 for(let i=0;i<eligible.length;i++){const g=eligible[i],members=g.members.filter(s=>s.blockCount&&state.pairs[s.pairIndex]);if($('#nullBlocks').value==='all'){for(const s of members)for(let blockIndex=0;blockIndex<s.blockCount;blockIndex++)tasks.push({g,s,blockIndex})}else{const random=W.rng(seed+i*7919);let pick=Math.floor(random()*W.sum(members.map(s=>s.blockCount)));for(const s of members){if(pick<s.blockCount){tasks.push({g,s,blockIndex:pick});break}pick-=s.blockCount}}}
 state.controls=[];state.nullRunning=true;$('#runNull').disabled=true;$('#cancelNull').hidden=false;let worker;
 try{worker=makeWorker();state.nullWorker=worker;for(let i=0;i<tasks.length;i++){if(!state.nullRunning)break;const {g,s,blockIndex}=tasks[i];$('#nullStatus').textContent=`Block ${i+1}/${tasks.length} · ${dateText(g.start)} · preparing`;
 try{const result=await request(worker,{kind:'controls',pair:state.pairs[s.pairIndex],settings:state.settings,methods,count,seed:seed+i*7919,blockIndex},p=>{$('#nullStatus').textContent=`Block ${i+1}/${tasks.length} · ${dateText(g.start)} · ${p.method} ${p.done}/${p.total}`});state.controls.push({groupId:g.id,date:dateText(g.start),source:g.source,...result});drawSpectrum(result);renderNullResults()}catch(e){if(!state.nullRunning)break;state.controls.push({groupId:g.id,date:dateText(g.start),source:g.source,error:e.message})}}
 $('#nullStatus').textContent=`${state.nullRunning?'Complete':'Stopped'} · ${state.controls.length} blocks attempted. q values cover completed blocks in this run only.`;
 }catch(e){$('#nullStatus').textContent=e.message}finally{stopWorker(worker);state.nullWorker=null;state.nullRunning=false;$('#runNull').disabled=false;$('#cancelNull').hidden=true;renderNullResults()}}
function nullRows(){const rows=state.controls.flatMap(c=>(c.results||[]).map(r=>({date:c.date,source:c.source,blockStart:timeText(c.start),blockEnd:timeText(c.end),...r})));for(const source of ['Device MV','Flow-derived'])for(const method of ['phase','iaaft']){const rr=rows.filter(r=>r.source===source&&r.method===method);for(const k of ['contrast','slowPower','repeatPeak']){const q=W.bh(rr.map(r=>r.metrics[k].p));rr.forEach((r,i)=>r.metrics[k].q=q[i])}}return rows}
function renderNullResults(){const rows=nullRows();$('#nullResults').innerHTML=rows.length?`<table><thead><tr><th>Period / block start</th><th>Method</th><th>N</th><th>Contrast obs / null</th><th>Contrast p / q</th><th>Slow power p / q</th><th>Repeat peak p / q</th><th>Spectrum error</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date}<br><span class="hint">${esc(r.blockStart)}</span></td><td>${r.method}</td><td>${r.count}</td><td>${fmt(r.metrics.contrast.observed)} / ${fmt(r.metrics.contrast.median)}</td><td>${fmt(r.metrics.contrast.p,3)} / ${fmt(r.metrics.contrast.q,3)}</td><td>${fmt(r.metrics.slowPower.p,3)} / ${fmt(r.metrics.slowPower.q,3)}</td><td>${fmt(r.metrics.repeatPeak.p,3)} / ${fmt(r.metrics.repeatPeak.q,3)}</td><td>${pct(r.spectralError)}</td></tr>`).join('')}</tbody></table><p class="hint">Significance is against a limited stationary surrogate model. It is not evidence of a specific mechanism. A low contrast p-value may occur with very small absolute waves. IAAFT spectrum error is relative Fourier-amplitude mismatch.</p>`:'';for(const c of state.controls.filter(c=>c.error)){const p=document.createElement('p');p.className='hint';p.textContent=`${c.date}: ${c.error}`;$('#nullResults').append(p)}}
function drawSpectrum(r){const c=$('#spectrumCanvas');c.hidden=false;const {ctx,width,height}=setupCanvas(c,260),p={left:55,right:20,top:25,bottom:30},half=width/2;const period=r.spectrum.period,power=r.spectrum.power,indices=period.map((p,i)=>p>=3&&p<=30?i:-1).filter(i=>i>=0),max=Math.max(1e-9,...indices.map(i=>power[i]));ctx.fillStyle=colors.muted;ctx.fillText('Envelope spectrum · periods 3–30 minutes',10,15);ctx.fillText('Envelope autocorrelation · lags 0–25 minutes',half+10,15);ctx.strokeStyle=colors.purple;ctx.beginPath();indices.reverse().forEach((i,j)=>{const x=40+(period[i]-3)/27*(half-60),y=height-30-power[i]/max*(height-60);j?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.strokeStyle=colors.device;ctx.beginPath();r.acf.forEach((v,i)=>{const x=half+35+i/(r.acf.length-1)*(half-60),y=height-40-(v+.5)/1.5*(height-70);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=colors.muted;for(const v of [3,10,20,30])ctx.fillText(String(v),40+(v-3)/27*(half-60),height-8);for(const v of [0,5,10,15,20,25])ctx.fillText(String(v),half+35+v/25*(half-60),height-8)}
function download(name,text,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(rows){const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const cell=x=>'"'+String(x??'').replace(/"/g,'""')+'"';return[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n')}
function exportNights(){const keys=['source','tag','duration','usableSeconds','usableFraction','amplitude','relativeAmplitude','fraction','relativeFraction','packetCount','longPackets','packetRate','packetDuration','contrast','carrier'];download('wave-periods.csv',csv(state.visible.map(g=>({device_start:new Date(g.start).toISOString().replace('Z',''),display_start:timeText(g.start),type:g.isNap?'Nap':'Night',sessions:g.members.length,...Object.fromEntries(keys.map(k=>[k,g[k]])),notes:g.note||'',settings:JSON.stringify(state.settings),version:W.VERSION}))))}
function exportPackets(){if(!state.selected)return;download('wave-packets.csv',csv(state.selected.packets.map(p=>({...p,device_start:new Date(p.start).toISOString().replace('Z',''),device_end:new Date(p.end).toISOString().replace('Z',''),display_start:timeText(p.start),threshold:state.settings.threshold,band:state.settings.band,smoothing:state.settings.smooth}))))}
function exportControls(){download('wave-controls.csv',csv(nullRows().map(r=>({date:r.date,source:r.source,blockStart:r.blockStart,blockEnd:r.blockEnd,method:r.method,count:r.count,seed:r.seed,spectralError:r.spectralError,...Object.fromEntries(Object.entries(r.metrics).flatMap(([k,v])=>Object.entries(v).map(([stat,x])=>[k+'_'+stat,x])))}))))}
function saveResults(){const sessions=state.sessions.map(({_detail,...s})=>s);download('wave-results.json',JSON.stringify({schema:'wave-results',version:1,engine:W.VERSION,settings:state.settings,sessions,annotations:state.annotations,controls:state.controls},null,0),'application/json')}
async function restoreResults(file){try{
 if(file.size>50*1024*1024)throw Error('Saved-results file is too large');
 const data=JSON.parse(await file.text()),validated=W.validateSnapshot(data);
 cancelBatch();cancelDetails();cancelNull();state.sessions=validated.sessions;state.pairs=[];state.queued=[];state.demo=false;state.annotations=validated.annotations;state.controls=[];state.settings=validated.settings;
 showSettings(state.settings);$('#process').disabled=true;renderResults(true);$('#night').hidden=true;
 status('Saved summaries and labels restored. Original EDF files are needed for detailed waveforms and new controls. Saved control tables remain in the JSON export; new control runs start fresh.');
 }catch(e){status(e.message,true)}}
function demo(){if(state.processing)return;cancelDetails();cancelNull();state.settings={...W.DEFAULTS};showSettings(state.settings);state.demo=true;state.sessions=[];state.pairs=[];state.controls=[];state.annotations={};const random=W.rng(25);for(let day=0;day<16;day++){const n=5400,start=Date.UTC(2025,0,day+1,22),x=Float64Array.from({length:n},(_,i)=>{const t=i*2,packet=.15+.95*Math.max(0,Math.sin(t/800))**2,amplitude=day<11?packet:packet*.25;return 5.2+amplitude*Math.sin(2*Math.PI*t/(43+day%4))+.09*(random()-.5)+.12*Math.sin(t/1100)}),r=W.analyzeSignal({mv:x,start,duration:n*2,source:'Device MV',support:day<11?'Synthetic larger waves':'Synthetic smaller waves',leak:new Float64Array(n),epap:new Float64Array(n).fill(7),pressure:new Float64Array(n).fill(8)});state.sessions.push({...r.meta,id:'synthetic-'+day,packets:r.packets,relativePackets:r.relativePackets,preview:W.compact(r,600),_detail:{...r,...r.meta,variants:[],flowCheck:null},pairIndex:-1})}$('#night').hidden=true;renderResults(true);status('Synthetic demonstration only — 16 constructed recordings. Import your own EDF data to replace these.');$('#process').disabled=!state.queued.length}
function importPause(){return new Promise(resolve=>setTimeout(resolve,16))}
function beginImport(message){
 if(state.processing)return false;
 state.importing=true;
 for(const id of ['chooseFolder','chooseFiles','process','reset','demo','restore'])$('#'+id).disabled=true;
 $('#process').textContent='Preparing file list…';
 $('#status').classList.remove('ready');$('#status').classList.add('loading');
 $('#progress').hidden=false;$('#progress').removeAttribute('value');$('#progress').setAttribute('aria-label','Preparing selected files');
 status(message);return true;
}
function finishImport(message,error=false){
 state.importing=false;
 for(const id of ['chooseFolder','chooseFiles','reset','demo','restore'])$('#'+id).disabled=false;
 $('#process').disabled=!state.queued.length;
 $('#process').textContent=state.queued.length?`Process selected (${state.queued.length} files)`:'Process selected';
 $('#progress').hidden=true;$('#progress').max=100;$('#progress').value=0;$('#progress').setAttribute('aria-label','Analysis progress');
 $('#status').classList.remove('loading');$('#status').classList.toggle('ready',!error&&state.queued.length>0);
 status(message,error);$('#status').classList.toggle('ready',!error&&state.queued.length>0);
}
async function queue(files){
 if(state.processing)return;
 if(!state.importing)beginImport('Reading selected files…');
 try{
  const total=files.length,seen=new Set(state.queued.map(fileKey)),added=[];let ignored=0,duplicates=0;
  status(`Selection received · checking ${total.toLocaleString()} files…`);
  $('#progress').max=Math.max(1,total);$('#progress').value=0;await importPause();
  for(let i=0;i<total;i++){
   const f=files[i];if(!/_(PLD|BRP)\.edf$/i.test(f.name))ignored++;
   else{const k=fileKey(f);if(seen.has(k))duplicates++;else{seen.add(k);added.push(f)}}
   if((i+1)%400===0){$('#progress').value=i+1;status(`Checking files · ${(i+1).toLocaleString()} of ${total.toLocaleString()} · ${added.length.toLocaleString()} new PLD/BRP files found`);await importPause()}
  }
  for(const f of added)state.queued.push(f);
  finishImport(state.queued.length?`Ready to process · ${state.queued.length.toLocaleString()} PLD/BRP files queued. ${added.length.toLocaleString()} added, ${duplicates.toLocaleString()} duplicates and ${ignored.toLocaleString()} unrelated files skipped. Review settings, then press Process selected.`:`Selection checked · no PLD or BRP EDF files found among ${total.toLocaleString()} files. Select a DATALOG folder or PLD/BRP files.`);
 }catch(error){finishImport(`Could not prepare selected files: ${error.message}`,true)}
}
async function readEntry(entry,found){
 if(entry.isFile){const f=await new Promise((resolve,reject)=>entry.file(resolve,reject));found.push(f);if(found.length%250===0){status(`Reading folder contents · ${found.length.toLocaleString()} files found…`);await importPause()}return}
 if(entry.isDirectory){const reader=entry.createReader();while(true){const entries=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!entries.length)break;for(const e of entries)await readEntry(e,found)}}
}
function chooseInput(id){
 if(state.processing||state.importing)return;
 beginImport('Selecting files… Large folders may take a moment to list after you confirm your selection.');
 try{$('#'+id).click()}catch(error){finishImport(error.message,true)}
}
$('#chooseFolder').onclick=()=>chooseInput('folder');$('#chooseFiles').onclick=()=>chooseInput('files');
for(const id of ['folder','files']){
 $('#'+id).onchange=async e=>{await queue(e.target.files);e.target.value=''};
 $('#'+id).oncancel=()=>finishImport(state.queued.length?`Selection canceled · ${state.queued.length.toLocaleString()} files remain ready to process.`:'Selection canceled. Select data to begin.');
}
$('#drop').ondragover=e=>{e.preventDefault();if(!state.processing&&!state.importing)$('#drop').classList.add('drag')};
$('#drop').ondragleave=()=>$('#drop').classList.remove('drag');
$('#drop').ondrop=async e=>{
 e.preventDefault();$('#drop').classList.remove('drag');if(state.processing||state.importing)return;
 beginImport('Reading dropped files and folders…');
 try{
  // Capture entries before yielding: drag data is only readable during the drop event.
  const entries=Array.from(e.dataTransfer.items||[]).map(i=>i.webkitGetAsEntry?.()).filter(Boolean),files=Array.from(e.dataTransfer.files||[]);
  await importPause();
  if(entries.length){const all=[];for(const entry of entries)await readEntry(entry,all);await queue(all)}else await queue(files);
 }catch(error){finishImport(`Could not read dropped files: ${error.message}`,true)}
};
$('#drop').onkeydown=e=>{if(e.key==='Enter'&&e.target===$('#drop'))chooseInput('files')};

$('#process').onclick=processAll;$('#cancel').onclick=cancelBatch;$('#demo').onclick=demo;$('#restore').onclick=()=>$('#restoreInput').click();$('#restoreInput').onchange=e=>{if(e.target.files[0])restoreResults(e.target.files[0]);e.target.value=''};
$('#reset').onclick=()=>{cancelBatch();cancelDetails();cancelNull();state.rawToken=(state.rawToken||0)+1;if(state.rawWorker)stopWorker(state.rawWorker);state.queued=[];state.pairs=[];state.sessions=[];state.groups=[];state.visible=[];state.annotations={};state.controls=[];state.selected=null;$('#results').hidden=true;$('#process').disabled=true;$('#progress').hidden=true;issues([]);status('Cleared. No data retained in this page.')};
for(const id of ['dateFrom','dateTo','sourceFilter','typeFilter'])$('#'+id).onchange=()=>{state.scapePage=0;renderResults()};$('#filterReset').onclick=()=>{for(const id of ['dateFrom','dateTo'])$('#'+id).value='';$('#sourceFilter').value='all';$('#typeFilter').value='all';renderResults()};$$('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;$$('[data-view]').forEach(b=>b.classList.toggle('active',b===button));$$('.view').forEach(v=>v.hidden=v.id!==state.view);if(state.view==='longitudinal')renderTrends();if(state.view==='scape')renderScape()});$('#scapeMode').onchange=renderScape;$('#runCompare').onclick=compare;$('#csv').onclick=exportNights;$('#save').onclick=saveResults;$('#packetCsv').onclick=exportPackets;$('#nullCsv').onclick=exportControls;$('#runNull').onclick=runNull;$('#cancelNull').onclick=()=>{cancelNull();$('#nullStatus').textContent='Stopped. Completed control results retained.'};$('#closeNight').onclick=()=>{cancelDetails();if(state.rawWorker)stopWorker(state.rawWorker);state.selected=null;$('#night').hidden=true};$('#saveNote').onclick=()=>{if(!state.selected)return;state.annotations[state.selected.id]={tag:$('#nightTag').value.trim(),note:$('#nightNote').value.trim()};renderResults();$('#nightMeta').textContent='Label saved in this page. Use Save results to keep annotations after closing.'};$('#previous').onclick=()=>{const r=state.range;if(r)setRange(r.from-(r.to-r.from),r.from)};$('#next').onclick=()=>{const r=state.range;if(r)setRange(r.to,r.to+(r.to-r.from))};$('#zoomIn').onclick=()=>{const r=state.range;if(r){const q=(r.to-r.from)/4;setRange(r.from+q,r.to-q)}};$('#zoomOut').onclick=()=>{const r=state.range;if(r){const q=(r.to-r.from)/2;setRange(r.from-q,r.to+q)}};$('#whole').onclick=()=>{if(state.selected)setRange(state.selected.start,state.selected.end)};$('#rawSection').ontoggle=()=>{if($('#rawSection').open)loadRaw()};$$('#analysisSettings input,#analysisSettings select').forEach(e=>e.onchange=()=>{$('#settingsBadge').textContent=state.sessions.length?'Changed — reprocess to apply':'Settings updated'});let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{renderTrends();if(state.view==='scape')renderScape();if(state.selected){drawOverview();drawDetail();if($('#rawSection').open)drawRaw()}},150)});window.addEventListener('beforeunload',()=>{for(const w of [...state.workers])stopWorker(w)});

$('#trendSmooth').onchange=renderTrends;
