'use strict';
async function buffers(pair,needFlow=false){const pld=pair.pld?await pair.pld.arrayBuffer():null,hasMV=pld&&Wave.parseEDF(pld).channels.some(c=>/^MinVent(?:\.|$)/i.test(c.label));return{pld,brp:pair.brp&&(needFlow||!hasMV)?await pair.brp.arrayBuffer():null}}
function summarizeResult(r){return{...r.meta,packets:r.packets,relativePackets:r.relativePackets,preview:Wave.compact(r,600)}}
function sensitivity(r,o){const valid=r.valid,base=r.base,n=r.x.length,count=Wave.sum(valid),fraction=(a,mask=valid)=>{let good=0,total=0;for(let i=0;i<n;i++)if(mask[i]){total++;if(a[i]>=o.threshold)good++}return{fraction:total?good/total:null,seconds:total*2}};const variants=[['Selected band',r.a],['30–90 s band',Wave.envelope(Wave.filter(r.x,'narrow'),o.smooth)],['20–180 s band',Wave.envelope(Wave.filter(r.x,'wide'),o.smooth)],['Band RMS',Float64Array.from(Wave.rolling(Float64Array.from(r.y,v=>v*v),o.smooth),v=>Math.sqrt(Math.max(0,v)))]];const cap=Wave.quantile(Wave.select(r.x,valid),.99),clipped=Wave.envelope(Wave.filter(Float64Array.from(r.x,v=>Math.min(v,cap)),o.band),o.smooth);variants.push(['Clip largest 1% of MV',clipped]);const rows=variants.map(([name,a])=>({name,...fraction(a),correlation:Wave.corr(r.a,a,valid)}));if(r.leak){const mask=Wave.expandBad(Uint8Array.from(r.leak,v=>!Number.isFinite(v)||v>6),60);rows.push({name:'Leak ≤6 L/min',...fraction(r.a,Uint8Array.from(valid,(v,i)=>v&&!mask[i]))})}if(r.epap){const mask=valid.slice();for(let i=0;i<n;i++){let lo=Infinity,hi=-Infinity;for(let j=Math.max(0,i-30);j<Math.min(n,i+31);j++){lo=Math.min(lo,r.epap[j]);hi=Math.max(hi,r.epap[j])}mask[i]=valid[i]&&hi-lo<=.2}rows.push({name:'Locally stable EPAP',...fraction(r.a,mask)})}return rows}
self.onmessage=async({data:m})=>{const send=(type,data)=>self.postMessage({id:m.id,type,...data});try{
 const o={...Wave.DEFAULTS,...m.settings};
 if(m.kind==='raw'){
  if(!m.pair.brp)throw Error('No matching BRP file was selected');const edf=Wave.parseEDF(await m.pair.brp.arrayBuffer()),ch=edf.channels.find(c=>/^Flow(?:\.|$)/i.test(c.label));if(!ch)throw Error('No raw airflow signal');const c=edf.read(ch),scale=/l\/s/i.test(c.unit)?60:/l\/min/i.test(c.unit)?1:null;if(scale===null)throw Error('Unsupported flow units');const from=Math.max(0,(m.from-edf.start)/1000),to=Math.min(edf.duration,(m.to-edf.start)/1000),first=Math.floor(from*c.fs),last=Math.ceil(to*c.fs),stride=Math.max(1,Math.ceil((last-first)/2400)),points=[];for(let b=first;b<last;b+=stride){let lo=Infinity,hi=-Infinity,s=0,e=Math.min(last,b+stride);for(let i=b;i<e;i++){const v=c.data[i]*scale;lo=Math.min(lo,v);hi=Math.max(hi,v);s+=v}points.push([edf.start+(b+e)/2/c.fs*1000,lo,hi,s/(e-b)])}send('done',{result:{points,fs:c.fs,from:edf.start+from*1000,to:edf.start+to*1000}});return;
 }
 const b=await buffers(m.pair,o.source==='flow'),input=Wave.prepare(b.pld,b.brp,o),r=Wave.analyzeSignal(input,o);if(r.skipped){send('done',{result:r});return}
 if(m.kind==='analyze'){
  const primary=input.source==='Device MV'?b.pld:b.brp,digest=await crypto.subtle.digest('SHA-256',primary),hash=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');send('done',{result:{...summarizeResult(r),hash}});return;
 }
 if(m.kind==='detail'){
  const variants=sensitivity(r,o);let flowCheck=null,flowEnvelope=null;
  if(m.pair.brp&&input.source==='Device MV')try{const edf=Wave.parseEDF(await m.pair.brp.arrayBuffer()),fm=Wave.flowMV(edf),aligned=new Float64Array(r.x.length),offset=(input.start-edf.start)/2000;for(let i=0;i<aligned.length;i++){const p=i+offset,j=Math.floor(p),f=p-j;aligned[i]=j<0||j>=fm.mv.length?0:fm.mv[j]+(fm.mv[Math.min(j+1,fm.mv.length-1)]-fm.mv[j])*f}flowEnvelope=Wave.envelope(Wave.filter(aligned,o.band),o.smooth);const mask=r.valid.slice();for(let i=0;i<mask.length;i++)if(i+offset<0||i+offset>=fm.mv.length-1)mask[i]=0;flowCheck={r:Wave.corr(flowEnvelope,r.a,mask),offsetSeconds:(edf.start-input.start)/1000}}catch(e){flowCheck={error:e.message}}
  send('done',{result:{...summarizeResult(r),x:r.x,a:r.a,base:r.base,relative:r.relative,valid:r.valid,leak:r.leak,pressure:r.pressure,epap:r.epap,flowLimit:r.flowLimit,blocks:r.blocks,thresholds:r.meta.variants,variants,flowCheck,flowEnvelope}});return;
 }
 if(m.kind==='controls'){
  if(!r.blocks.length)throw Error('No uninterrupted low-leak 90-minute block in this session');const pick=Wave.rng(m.seed)(),index=Number.isInteger(m.blockIndex)?m.blockIndex:Math.floor(pick*r.blocks.length);if(index<0||index>=r.blocks.length)throw Error('Requested control block does not exist');const startIndex=r.blocks[index],y=r.y.slice(startIndex,startIndex+2700),results=[];
  for(const method of m.methods){const result=Wave.control(y,o,method,m.count,m.seed+(method==='iaaft'?104729:0),(done,total)=>send('progress',{done,total,method}));results.push(result)}
  const env=Wave.envelope(y,o.smooth).slice(90,-90),spec=Wave.spectrum(env),acf=Wave.acf(env);send('done',{result:{start:input.start+startIndex*2000,end:input.start+(startIndex+2700)*2000,results,spectrum:{period:Array.from(spec.freq,(f)=>f?1/f/60:null),power:Array.from(spec.power)},acf:Array.from(acf)}});return;
 }
 throw Error('Unknown worker request');
}catch(e){send('error',{error:e.message||String(e)})}};
